# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, MainWindow, **kw):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commentTree = QtWidgets.QTreeWidget(self.centralwidget)
        self.commentTree.setHeaderLabels(["用户", "内容", "时间"])
        self.commentTree.setGeometry(QtCore.QRect(0, 250, 790, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentTree.sizePolicy().hasHeightForWidth())
        self.commentTree.setSizePolicy(sizePolicy)
        self.commentTree.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.commentTree.setObjectName("commentTree")
        self.commentTree.setColumnWidth(0, 100)
        self.commentTree.setColumnWidth(1, 540)
        self.commentTree.setColumnWidth(2, 130)
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(660, 20, 131, 21))
        self.btnLoad.setObjectName("btnLoad")
        self.textContent = QtWidgets.QTextBrowser(self.centralwidget)
        self.textContent.setGeometry(QtCore.QRect(0, 80, 790, 171))
        self.textContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textContent.setOverwriteMode(False)
        self.textContent.setPlaceholderText("")
        self.textContent.setObjectName("textContent")
        self.textUid = QtWidgets.QLabel(self.centralwidget)
        self.textUid.setGeometry(QtCore.QRect(10, 0, 61, 21))
        self.textUid.setObjectName("textUid")
        self.textTime = QtWidgets.QLabel(self.centralwidget)
        self.textTime.setGeometry(QtCore.QRect(70, 0, 790, 21))
        self.textTime.setObjectName("textTime")
        self.textTitle = QtWidgets.QTextEdit(self.centralwidget)
        self.textTitle.setGeometry(QtCore.QRect(0, 40, 790, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textTitle.setFont(font)
        self.textTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textTitle.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textTitle.setReadOnly(True)
        self.textTitle.setObjectName("textTitle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(650, 0, 31, 21)) #
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 651, 16))
        self.label_2.setObjectName("label_2")
        self.numOid = QtWidgets.QSpinBox(self.centralwidget)
        self.numOid.setGeometry(QtCore.QRect(690, 0, 101, 22))
        self.numOid.setProperty("minimum", 1)
        self.numOid.setProperty("maximum", 16777215)
        self.numOid.setObjectName("numOid")
        self.numOid.setProperty("value", kw['initial'])
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 528, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow, **kw)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, **kw):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OBARC Viewer"))
        self.btnLoad.setText(_translate("MainWindow", "加载 (F7)"))
        self.textContent.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">"
                                            + kw['content'] +
                                            "</p></body></html>"))
        self.textUid.setText(_translate("MainWindow", f"uid{kw['uid']}"))
        self.textTime.setText(_translate("MainWindow", f"{kw['pub_time_f']} (存档时间 {kw['arc_time_f']})"
                                                       f"        标签: {kw['tag_str']}"))
        self.textTitle.setHtml(_translate("MainWindow",
                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                          "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">"
                                          f"{kw['title']}"
                                          "</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "ob"))
        self.label_2.setText(_translate("MainWindow", f"浏览 {kw['view']}   冷藏 {kw['fav']}    赞 {kw['like']}"
                                                      f"    频道号 {kw['channel_id']}    关联视频 ov{kw['attach_vid']}       {kw['gore']}"))
